import { Inter } from "next/font/google";
import "./globals.css";
import AppSessionProvider from "@/utils/AppSessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className=" max-w-4xl  mx-auto p-4 ">
          <AppSessionProvider>{children}</AppSessionProvider>
        </main>
      </body>
    </html>
  );
}
